### ISSUE TITLE
[UX] Navigation loss after input change

### ISSUE THREAD

**Issue by AntoninTripes** [Vixen51/rbm#186]
**Issue**
When going back to settings after input has been modified via controller you lose navigation

**Repro**

1. Use controller and launch any level via Level Table 
2. Pause game
3. Go to Settings
4. Change any Maneuver input
5. Go back to game by pressing [B] on controller
6. Pause game
7. Go to Settings
8. You lost navigation on controller
9. Go back [B] on controller
10. Go to Settings
11. You regained navigation on controller

**Comment by AntoninTripes** [comment]
Issue still present in current build, added repro steps for easier debugging.

**Comment by AntoninTripes** [comment]
Reassigned to @Vixen51

**Comment by Vixen51** [comment]
Done in CL4500

**Comment by Vixen51** [comment]
Better steps:

Main menu -> Settings -> Input -> select any element from grid -> Back -> Settings

**Comment by AntoninTripes** [comment]
Original issue as described in the ticket's repro steps still present in current build.
